name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to EC2
        run: |
          scp -r -i ~/.ssh/id_rsa ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/BetterMindCare-temp

      - name: Deploy + Restart on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            rm -rf ~/BetterMindCare
            mv ~/BetterMindCare-temp ~/BetterMindCare
            cd ~/BetterMindCare/src/backend
            npm install
            pm2 restart all || pm2 start server.js --name bmc-api
          EOF