name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: |
          cd src/backend
          npm install

      - name: Restart PM2 process
        run: |
          cd src/backend
          pm2 restart bmc-api || pm2 start server.js --name bmc-api